server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 703984239342-bf0e1psffdstp0fd8h5i26mi8tf47a56.apps.googleusercontent.com
            client-secret: CGZy3ch31X2lDrc0ih-P7iot
      resourceserver:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true