server:
  port: 8081
  servlet.context-path: /auth

oauth:
  clientId: R2dpxQ3vPrtfgF72
  clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
  redirectUris: http://localhost:8080/login/oauth2/code/

user:
  username: user
  password: password