server:
  port: 8081
  servlet.context-path: /auth

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

oauth:
  clientId: R2dpxQ3vPrtfgF72
  clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
  redirectUris: http://localhost:8080/login/oauth2/code/