server:
  port: 8082
  servlet.context-path: /ui1
  session:
    cookie:
      name: UISESSION1

spring:
  thymeleaf:
    cache: false
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          custom-client:
            client-id: oauth-sso-client
            client-secret: p2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C
            client-name: OAuth Client
            scope:
              - user_info
              - read
              - write
            provider: custom-provider
            redirect-uri: http://localhost:8082/ui1/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/user/me
            user-name-attribute: name
            user-info-authentication-method: header
