DROP TABLE IF EXISTS `OAUTH_ACCESS_TOKEN`;
DROP TABLE IF EXISTS `OAUTH_REFRESH_TOKEN `;

CREATE TABLE OAUTH_ACCESS_TOKEN (
  authentication_id VARCHAR(255) PRIMARY KEY,
  token_id VARCHAR(255),
  token LONGVARBINARY,
  user_name VARCHAR(255),
  client_id VARCHAR(255),
  authentication LONGVARBINARY,
  refresh_token VARCHAR(255)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  token_id VARCHAR(255),
  token LONGVARBINARY,
  authentication LONGVARBINARY
);