DROP TABLE IF EXISTS `USER_ROLES`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `ROLE`;

CREATE TABLE USER (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   USERNAME VARCHAR(50) UNIQUE NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   FIRSTNAME VARCHAR(50) NOT NULL,
   LASTNAME VARCHAR(50) NOT NULL,
   ACTIVATED BOOLEAN NOT NULL
);

CREATE TABLE ROLE (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE USER_ROLES (
   USER_ID INT NOT NULL,
   ROLE_ID INT NOT NULL
);

INSERT INTO ROLE(ID, ROLE) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE(ID, ROLE) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ACTIVATED)
VALUES (1, 'user', '$2y$12$YjMkhp8e/CfMMaLbNdRaFu3CPe1kYL03kpHyM4Fq8RAbo8kIMBYt6', 'User', 'User', TRUE );
INSERT INTO USER(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ACTIVATED)
VALUES (2, 'admin', '$2y$12$YjMkhp8e/CfMMaLbNdRaFu3CPe1kYL03kpHyM4Fq8RAbo8kIMBYt6', 'Admin', 'Admin', TRUE );
INSERT INTO USER(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ACTIVATED)
VALUES (3, 'disabled', '$2y$12$YjMkhp8e/CfMMaLbNdRaFu3CPe1kYL03kpHyM4Fq8RAbo8kIMBYt6', 'User', 'User', FALSE );

INSERT INTO USER_ROLES VALUES (1, 1);
INSERT INTO USER_ROLES VALUES (2, 1);
INSERT INTO USER_ROLES VALUES (2, 2);
INSERT INTO USER_ROLES VALUES (3, 1);
