server:
  port: 8080

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8081/sso-auth-server/.well-known/jwks.json

jwt:
  secretKey: 3778214125442A472D4B6150645367566B58703273357638792F423F4528482B
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApo79sLedpGkoCqKHvU6h
    6VvbO5w7VNVomUOwo7xdsFXHzvf7Zx7iF5AQP75cnPF5+H2F7FzDS0MXf9kXI20b
    WW+krXJD0HApy1q10w4pGMEtpQZZhGgSy4Ek8apA9K62aBTY1fweHLN8MLQr/n+S
    nRp6xQc+6E9RJxC8JVStKo/A5CfkVtEgfxDl9Bk2wt5y8U4dPkDRKuRI1hVuXsvh
    0LT0g95iMZwT/lymxNd9gm5AYBgU172FPHTq65ZiYOjO1JqU70uy4XcgZHT0WJ2O
    poH8jROEX6Cq+UptPHx3uJEUivf66jaf2e2HR7kOvBJsIygBf4F0JDjK2WHbgnyU
    5QIDAQAB
    -----END PUBLIC KEY-----