server:
  port: 8081
  servlet.context-path: /auth

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

oauth2:
  clientId: oauth-client
  clientSecret: p2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C

jwk:
  keyStore:
    location: myapp.jks
    password: mypass
  keyPair:
    alias: myexample
  keyId: mykeyID

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    io.netty: WARN
    com.example: DEBUG



