server:
  port: 8081
  servlet.context-path: /auth

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

oauth2:
  clientId: oauth-client
  clientSecret: p2s5v8y/B?E(H+MbPeShVmYq3t6w9z$C

jwt:
  secretKey: 3778214125442A472D4B6150645367566B58703273357638792F423F4528482B

