server:
  port: 8080

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:9000/auth/realms/myKeyCloak/protocol/openid-connect/certs

logging:
  level:
    org.springframework: WARN
    io.netty: WARN
    com.example: DEBUG