version: '3'

volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local

services:
  postgres:
    image: postgres
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: manager
    volumes:
      - pgadmin:/var/lib/pgadmin
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: manager
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 9000:8080
    depends_on:
      - postgres