server:
  port: 8080

spring:
  thymeleaf:
    cache: false

okta:
  oauth2:
    issuer: https://dev-753636.okta.com/oauth2/default
    client-id: 0oa2hrxljg77qt5z9357
    client-secret: KFdhcbYNFTN1Ix65b29WK29Pa-60onfEGxNmeIjz