server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/.well-known/jwks.json
          #public-key-location: classpath:my-key.pub

logging:
  level:
    org.springframework: WARN
    io.netty: WARN
    com.example: DEBUG