server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret-key: 3778214125442A472D4B6150645367566B58703273357638792F423F4528482B
  # token is valid 24 hours
  token-validity-in-seconds: 86400

logging:
  level:
    org.springframework: WARN
    com.example: DEBUG